// js/players-data.js

const PLAYERS_DATA = [
  {
    id: 1,
    name: "Emmanuel O.",
    positionBadge: "FW",
    positionTitle: "Attacking Midfielder / Winger",
    positionShort: "AM / CAM",
    age: 18,
    height: "178 cm",
    foot: "Right",
    goals: 14,
    location: "Kampala, Uganda",
    nationality: "Ugandan",
    status: "Available for Trials",
    image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ",
    statsSummary: { pace: 88, vision: 85 },
    currentAttributes: [88, 82, 85, 86, 52, 74],
    potentialAttributes: [94, 88, 91, 92, 60, 82]
  },
  {
    id: 2,
    name: "David K.",
    positionBadge: "DF",
    positionTitle: "Center Back",
    positionShort: "CB",
    age: 19,
    height: "186 cm",
    foot: "Right",
    goals: 3,
    location: "Kampala, Uganda",
    nationality: "Ugandan",
    status: "Available for Trials",
    image: "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ",
    statsSummary: { pace: 74, vision: 70 },
    currentAttributes: [74, 55, 68, 65, 86, 89],
    potentialAttributes: [80, 62, 75, 72, 92, 94]
  },
  {
    id: 3,
    name: "Joseph M.",
    positionBadge: "GK",
    positionTitle: "Goalkeeper",
    positionShort: "GK",
    age: 20,
    height: "191 cm",
    foot: "Left",
    goals: 0,
    location: "Kampala, Uganda",
    nationality: "Ugandan",
    status: "Signed / On Trial",
    image: "https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ",
    statsSummary: { pace: 60, vision: 78 },
    currentAttributes: [60, 40, 75, 62, 90, 84],
    potentialAttributes: [65, 45, 82, 70, 95, 88]
  },
  // Add Player 4, 5, 6 here anytime!
  {
    id: 4,
    name: "Brian A.",
    positionBadge: "MF",
    positionTitle: "Defensive Midfielder",
    positionShort: "CDM",
    age: 19,
    height: "182 cm",
    foot: "Right",
    goals: 4,
    location: "Kampala, Uganda",
    nationality: "Ugandan",
    status: "Available for Trials",
    image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ",
    statsSummary: { pace: 79, vision: 88 },
    currentAttributes: [79, 65, 88, 76, 82, 84],
    potentialAttributes: [85, 72, 93, 82, 89, 90]
  }
];